spring.cloud.stream:
  function:
    definition: movieProcessor
  bindings:
    movieProcessor-in-0:
      destination: moviedomainsnew
    movieProcessor-out-0:
      destination: movie-out-topic
  kafka:
    bindings:
      movieProcessor-in-0:
        consumer:
#          configuration:
#            value:
#              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      domainProcessor-out-0:
#        producer:
#          configuration:
#            value:
#              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092